// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Csharp_lab_16_CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ДобавлениеИПоиск - Используйте "ДобавлениеИПоискParams" для передачи параметров в этот метод.
        /// </summary>
        public void ДобавлениеИПоиск()
        {
            #region Variable Declarations
            WinEdit uITextBoxSearchTextEdit = this.UIForm1Window.UITextBoxSearchTextWindow.UITextBoxSearchTextEdit;
            WinWindow uITextBoxSearchTextWindow = this.UIForm1Window.UIНайтиПреподавателяGroup.UITextBoxSearchTextWindow;
            WinGroup uIНайтиПреподавателяGroup = this.UIForm1Window.UIНайтиПреподавателяWindow.UIНайтиПреподавателяGroup;
            WinButton uIНайтиButton = this.UIForm1Window.UIНайтиWindow.UIНайтиButton;
            WinButton uIОКButton = this.UIОшибкаWindow.UIОКWindow.UIОКButton;
            WinEdit uITextBoxSPEdit = this.UIForm1Window.UITextBoxSPWindow.UITextBoxSPEdit;
            WinEdit uITextBoxDEPARTMENTEdit = this.UIForm1Window.UITextBoxDEPARTMENTWindow.UITextBoxDEPARTMENTEdit;
            WinEdit uITextBoxNMBEdit = this.UIForm1Window.UITextBoxNMBWindow.UITextBoxNMBEdit;
            WinButton uIДобавитьButton = this.UIForm1Window.UIДобавитьWindow.UIДобавитьButton;
            WinButton uIОКButton1 = this.UIПредупреждениеWindow.UIОКWindow.UIОКButton;
            WinControl uIБазаДанныхDialog = this.UIБазаДанныхWindow.UIБазаДанныхDialog;
            WinButton uIОКButton2 = this.UIБазаДанныхWindow.UIОКWindow.UIОКButton;
            WinEdit uITextBoxNAMEEdit = this.UIForm1Window.UITextBoxNAMEWindow.UITextBoxNAMEEdit;
            WinGroup uIДобавитьПреподавателGroup = this.UIForm1Window.UIДобавитьПреподавателWindow.UIДобавитьПреподавателGroup;
            WinEdit uITextBoxLSTNAMEEdit = this.UIForm1Window.UITextBoxLSTNAMEWindow.UITextBoxLSTNAMEEdit;
            WinEdit uITextBoxPHONEEdit = this.UIForm1Window.UI__________Window.UITextBoxPHONEEdit;
            WinEdit uITextBoxEXPEdit = this.UIForm1Window.UITextBoxEXPWindow.UITextBoxEXPEdit;
            WinComboBox uIComboBoxGROUPComboBox = this.UIForm1Window.UIComboBoxGROUPWindow.UIComboBoxGROUPComboBox;
            WinButton uIДобавитьButton1 = this.UIForm1Window.UIДобавитьWindow1.UIДобавитьButton;
            #endregion

            // Последнее действие мыши не записано.

            // Перемещение  "textBoxSearchText" надпись в "textBoxSearchText" окно
            uITextBoxSearchTextWindow.EnsureClickable(new Point(30, 20));
            Mouse.StartDragging(uITextBoxSearchTextEdit, new Point(52, 12));
            Mouse.StopDragging(uITextBoxSearchTextWindow, new Point(30, 20));

            // Перемещение  "textBoxSearchText" окно в "Найти Преподавателя" группа
            uIНайтиПреподавателяGroup.EnsureClickable(new Point(67, 40));
            Mouse.StartDragging(uITextBoxSearchTextWindow, new Point(-44, 20));
            Mouse.StopDragging(uIНайтиПреподавателяGroup, new Point(67, 40));

            // Тип "Дмитрий" в "textBoxSearchText" надпись
            uITextBoxSearchTextEdit.Text = this.ДобавлениеИПоискParams.UITextBoxSearchTextEditText;

            // Щелкните "Найти" кнопка
            Mouse.Click(uIНайтиButton, new Point(17, 10));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, new Point(45, 14));

            // Тип "QWE" в "textBoxSearchText" надпись
            uITextBoxSearchTextEdit.Text = this.ДобавлениеИПоискParams.UITextBoxSearchTextEditText1;

            // Щелкните "Найти" кнопка
            Mouse.Click(uIНайтиButton, new Point(34, 2));

            // Тип "Alex" в "textBoxSearchText" надпись
            uITextBoxSearchTextEdit.Text = this.ДобавлениеИПоискParams.UITextBoxSearchTextEditText2;

            // Щелкните "Найти" кнопка
            Mouse.Click(uIНайтиButton, new Point(22, 7));

            // Тип "9999-ИВТ" в "textBoxSP" надпись
            uITextBoxSPEdit.Text = this.ДобавлениеИПоискParams.UITextBoxSPEditText;

            // Тип "ИиПО" в "textBoxDEPARTMENT" надпись
            uITextBoxDEPARTMENTEdit.Text = this.ДобавлениеИПоискParams.UITextBoxDEPARTMENTEditText;

            // Тип "99999" в "textBoxNMB" надпись
            uITextBoxNMBEdit.Text = this.ДобавлениеИПоискParams.UITextBoxNMBEditText;

            // Щелкните "Добавить" кнопка
            Mouse.Click(uIДобавитьButton, new Point(46, 4));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton1, new Point(31, 8));

            // Тип "6-ИВТ" в "textBoxSP" надпись
            uITextBoxSPEdit.Text = this.ДобавлениеИПоискParams.UITextBoxSPEditText1;

            // Щелкните "Добавить" кнопка
            Mouse.Click(uIДобавитьButton, new Point(26, 14));

            // Щелкните "База Данных" Dialog
            Mouse.Click(uIБазаДанныхDialog, new Point(197, 126));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton2, new Point(35, 12));

            // Тип "Евгений" в "textBoxNAME" надпись
            uITextBoxNAMEEdit.Text = this.ДобавлениеИПоискParams.UITextBoxNAMEEditText;

            // Щелкните "Добавить Преподавателя" группа
            Mouse.Click(uIДобавитьПреподавателGroup, new Point(129, 57));

            // Тип "Довакин" в "textBoxLSTNAME" надпись
            uITextBoxLSTNAMEEdit.Text = this.ДобавлениеИПоискParams.UITextBoxLSTNAMEEditText;

            // Тип "(382) 749-2387" в "textBoxPHONE" надпись
            uITextBoxPHONEEdit.Text = this.ДобавлениеИПоискParams.UITextBoxPHONEEditText;

            // Тип "9" в "textBoxPHONE" надпись
            Keyboard.SendKeys(uITextBoxPHONEEdit, this.ДобавлениеИПоискParams.UITextBoxPHONEEditSendKeys, ModifierKeys.None);

            // Тип "Junior" в "textBoxEXP" надпись
            uITextBoxEXPEdit.Text = this.ДобавлениеИПоискParams.UITextBoxEXPEditText;

            // Выберите "6-ИВТ" в "comboBoxGROUP" поле со списком
            uIComboBoxGROUPComboBox.SelectedItem = this.ДобавлениеИПоискParams.UIComboBoxGROUPComboBoxSelectedItem;

            // Щелкните "Добавить" кнопка
            Mouse.Click(uIДобавитьButton1, new Point(21, 10));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton2, new Point(38, 3));

            // Перемещение  "textBoxSearchText" надпись в "Найти Преподавателя" группа
            uIНайтиПреподавателяGroup.EnsureClickable(new Point(59, 39));
            Mouse.StartDragging(uITextBoxSearchTextEdit, new Point(83, 4));
            Mouse.StopDragging(uIНайтиПреподавателяGroup, new Point(59, 39));
        }
        
        /// <summary>
        /// Метод добавляет преподавателя в БД
        /// </summary>
        public void ДобавлениеПреподавателя()
        {
            #region Variable Declarations
            WinEdit uITextBoxNAMEEdit = this.UIForm1Window.UITextBoxNAMEWindow.UITextBoxNAMEEdit;
            WinEdit uITextBoxLSTNAMEEdit = this.UIForm1Window.UITextBoxLSTNAMEWindow.UITextBoxLSTNAMEEdit;
            WinEdit uITextBoxPHONEEdit = this.UIForm1Window.UI__________Window.UITextBoxPHONEEdit;
            WinEdit uITextBoxEXPEdit = this.UIForm1Window.UITextBoxEXPWindow.UITextBoxEXPEdit;
            WinComboBox uIComboBoxGROUPComboBox = this.UIForm1Window.UIComboBoxGROUPWindow.UIComboBoxGROUPComboBox;
            WinButton uIДобавитьButton = this.UIForm1Window.UIДобавитьWindow1.UIДобавитьButton;
            WinButton uIОКButton = this.UIБазаДанныхWindow.UIОКWindow.UIОКButton;
            #endregion

            // Тип "Нэйтан" в "textBoxNAME" надпись
            uITextBoxNAMEEdit.Text = this.ДобавлениеПреподавателяParams.UITextBoxNAMEEditText;

            // Тип "Джонс" в "textBoxLSTNAME" надпись
            uITextBoxLSTNAMEEdit.Text = this.ДобавлениеПреподавателяParams.UITextBoxLSTNAMEEditText;

            // Тип "(439) 587-3458" в "textBoxPHONE" надпись
            uITextBoxPHONEEdit.Text = this.ДобавлениеПреподавателяParams.UITextBoxPHONEEditText;

            // Тип "459" в "textBoxPHONE" надпись
            Keyboard.SendKeys(uITextBoxPHONEEdit, this.ДобавлениеПреподавателяParams.UITextBoxPHONEEditSendKeys, ModifierKeys.None);

            // Тип "Master" в "textBoxEXP" надпись
            uITextBoxEXPEdit.Text = this.ДобавлениеПреподавателяParams.UITextBoxEXPEditText;

            // Выберите "17-ИВТ-2" в "comboBoxGROUP" поле со списком
            uIComboBoxGROUPComboBox.SelectedItem = this.ДобавлениеПреподавателяParams.UIComboBoxGROUPComboBoxSelectedItem;

            // Щелкните "Добавить" кнопка
            Mouse.Click(uIДобавитьButton, new Point(34, 8));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, new Point(42, 16));
        }
        
        /// <summary>
        /// Метод добавления преподавателя в БД
        /// </summary>
        public void ДобавлениеПреподавателяНовое()
        {
            #region Variable Declarations
            WinEdit uITextBoxNAMEEdit = this.UIForm1Window.UITextBoxNAMEWindow.UITextBoxNAMEEdit;
            WinEdit uITextBoxLSTNAMEEdit = this.UIForm1Window.UITextBoxLSTNAMEWindow.UITextBoxLSTNAMEEdit;
            WinEdit uITextBoxPHONEEdit = this.UIForm1Window.UI__________Window.UITextBoxPHONEEdit;
            WinEdit uITextBoxEXPEdit = this.UIForm1Window.UITextBoxEXPWindow.UITextBoxEXPEdit;
            WinComboBox uIComboBoxGROUPComboBox = this.UIForm1Window.UIComboBoxGROUPWindow.UIComboBoxGROUPComboBox;
            WinButton uIДобавитьButton = this.UIForm1Window.UIДобавитьWindow1.UIДобавитьButton;
            WinButton uIОКButton = this.UIБазаДанныхWindow.UIОКWindow.UIОКButton;
            #endregion

            // Тип "Нэйтан" в "textBoxNAME" надпись
            uITextBoxNAMEEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxNAMEEditText;

            // Тип "Джонс" в "textBoxLSTNAME" надпись
            uITextBoxLSTNAMEEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxLSTNAMEEditText;

            // Тип "(439) 587-3458" в "textBoxPHONE" надпись
            uITextBoxPHONEEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxPHONEEditText;

            // Тип "459" в "textBoxPHONE" надпись
            Keyboard.SendKeys(uITextBoxPHONEEdit, this.ДобавлениеПреподавателяНовоеParams.UITextBoxPHONEEditSendKeys, ModifierKeys.None);

            // Тип "Master" в "textBoxEXP" надпись
            uITextBoxEXPEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxEXPEditText;

            // Выберите "17-ИВТ-2" в "comboBoxGROUP" поле со списком
            uIComboBoxGROUPComboBox.SelectedItem = this.ДобавлениеПреподавателяНовоеParams.UIComboBoxGROUPComboBoxSelectedItem;

            // Щелкните "Добавить" кнопка
            Mouse.Click(uIДобавитьButton, new Point(34, 8));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, new Point(42, 16));

            // Тип "Индиана" в "textBoxNAME" надпись
            uITextBoxNAMEEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxNAMEEditText1;

            // Тип "Джонс" в "textBoxLSTNAME" надпись
            uITextBoxLSTNAMEEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxLSTNAMEEditText1;

            // Тип "(435) 943-8573" в "textBoxPHONE" надпись
            uITextBoxPHONEEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxPHONEEditText1;

            // Тип "9" в "textBoxPHONE" надпись
            Keyboard.SendKeys(uITextBoxPHONEEdit, this.ДобавлениеПреподавателяНовоеParams.UITextBoxPHONEEditSendKeys1, ModifierKeys.None);

            // Тип "Master" в "textBoxEXP" надпись
            uITextBoxEXPEdit.Text = this.ДобавлениеПреподавателяНовоеParams.UITextBoxEXPEditText1;

            // Выберите "18-ПРИ" в "comboBoxGROUP" поле со списком
            uIComboBoxGROUPComboBox.SelectedItem = this.ДобавлениеПреподавателяНовоеParams.UIComboBoxGROUPComboBoxSelectedItem1;

            // Щелкните "Добавить" кнопка
            Mouse.Click(uIДобавитьButton, new Point(22, 7));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, new Point(22, 12));
        }
        
        #region Properties
        public virtual ДобавлениеИПоискParams ДобавлениеИПоискParams
        {
            get
            {
                if ((this.mДобавлениеИПоискParams == null))
                {
                    this.mДобавлениеИПоискParams = new ДобавлениеИПоискParams();
                }
                return this.mДобавлениеИПоискParams;
            }
        }
        
        public virtual ДобавлениеПреподавателяParams ДобавлениеПреподавателяParams
        {
            get
            {
                if ((this.mДобавлениеПреподавателяParams == null))
                {
                    this.mДобавлениеПреподавателяParams = new ДобавлениеПреподавателяParams();
                }
                return this.mДобавлениеПреподавателяParams;
            }
        }
        
        public virtual ДобавлениеПреподавателяНовоеParams ДобавлениеПреподавателяНовоеParams
        {
            get
            {
                if ((this.mДобавлениеПреподавателяНовоеParams == null))
                {
                    this.mДобавлениеПреподавателяНовоеParams = new ДобавлениеПреподавателяНовоеParams();
                }
                return this.mДобавлениеПреподавателяНовоеParams;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        
        public UIОшибкаWindow UIОшибкаWindow
        {
            get
            {
                if ((this.mUIОшибкаWindow == null))
                {
                    this.mUIОшибкаWindow = new UIОшибкаWindow();
                }
                return this.mUIОшибкаWindow;
            }
        }
        
        public UIПредупреждениеWindow UIПредупреждениеWindow
        {
            get
            {
                if ((this.mUIПредупреждениеWindow == null))
                {
                    this.mUIПредупреждениеWindow = new UIПредупреждениеWindow();
                }
                return this.mUIПредупреждениеWindow;
            }
        }
        
        public UIБазаДанныхWindow UIБазаДанныхWindow
        {
            get
            {
                if ((this.mUIБазаДанныхWindow == null))
                {
                    this.mUIБазаДанныхWindow = new UIБазаДанныхWindow();
                }
                return this.mUIБазаДанныхWindow;
            }
        }
        #endregion
        
        #region Fields
        private ДобавлениеИПоискParams mДобавлениеИПоискParams;
        
        private ДобавлениеПреподавателяParams mДобавлениеПреподавателяParams;
        
        private ДобавлениеПреподавателяНовоеParams mДобавлениеПреподавателяНовоеParams;
        
        private UIForm1Window mUIForm1Window;
        
        private UIОшибкаWindow mUIОшибкаWindow;
        
        private UIПредупреждениеWindow mUIПредупреждениеWindow;
        
        private UIБазаДанныхWindow mUIБазаДанныхWindow;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "ДобавлениеИПоиск"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class ДобавлениеИПоискParams
    {
        
        #region Fields
        /// <summary>
        /// Тип "Дмитрий" в "textBoxSearchText" надпись
        /// </summary>
        public string UITextBoxSearchTextEditText = "Дмитрий";
        
        /// <summary>
        /// Тип "QWE" в "textBoxSearchText" надпись
        /// </summary>
        public string UITextBoxSearchTextEditText1 = "QWE";
        
        /// <summary>
        /// Тип "Alex" в "textBoxSearchText" надпись
        /// </summary>
        public string UITextBoxSearchTextEditText2 = "Alex";
        
        /// <summary>
        /// Тип "9999-ИВТ" в "textBoxSP" надпись
        /// </summary>
        public string UITextBoxSPEditText = "9999-ИВТ";
        
        /// <summary>
        /// Тип "ИиПО" в "textBoxDEPARTMENT" надпись
        /// </summary>
        public string UITextBoxDEPARTMENTEditText = "ИиПО";
        
        /// <summary>
        /// Тип "99999" в "textBoxNMB" надпись
        /// </summary>
        public string UITextBoxNMBEditText = "99999";
        
        /// <summary>
        /// Тип "6-ИВТ" в "textBoxSP" надпись
        /// </summary>
        public string UITextBoxSPEditText1 = "6-ИВТ";
        
        /// <summary>
        /// Тип "Евгений" в "textBoxNAME" надпись
        /// </summary>
        public string UITextBoxNAMEEditText = "Евгений";
        
        /// <summary>
        /// Тип "Довакин" в "textBoxLSTNAME" надпись
        /// </summary>
        public string UITextBoxLSTNAMEEditText = "Довакин";
        
        /// <summary>
        /// Тип "(382) 749-2387" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditText = "(382) 749-2387";
        
        /// <summary>
        /// Тип "9" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditSendKeys = "9";
        
        /// <summary>
        /// Тип "Junior" в "textBoxEXP" надпись
        /// </summary>
        public string UITextBoxEXPEditText = "Junior";
        
        /// <summary>
        /// Выберите "6-ИВТ" в "comboBoxGROUP" поле со списком
        /// </summary>
        public string UIComboBoxGROUPComboBoxSelectedItem = "6-ИВТ";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "ДобавлениеПреподавателя"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class ДобавлениеПреподавателяParams
    {
        
        #region Fields
        /// <summary>
        /// Тип "Нэйтан" в "textBoxNAME" надпись
        /// </summary>
        public string UITextBoxNAMEEditText = "Нэйтан";
        
        /// <summary>
        /// Тип "Джонс" в "textBoxLSTNAME" надпись
        /// </summary>
        public string UITextBoxLSTNAMEEditText = "Джонс";
        
        /// <summary>
        /// Тип "(439) 587-3458" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditText = "(439) 587-3458";
        
        /// <summary>
        /// Тип "459" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditSendKeys = "459";
        
        /// <summary>
        /// Тип "Master" в "textBoxEXP" надпись
        /// </summary>
        public string UITextBoxEXPEditText = "Master";
        
        /// <summary>
        /// Выберите "17-ИВТ-2" в "comboBoxGROUP" поле со списком
        /// </summary>
        public string UIComboBoxGROUPComboBoxSelectedItem = "17-ИВТ-2";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "ДобавлениеПреподавателяНовое"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class ДобавлениеПреподавателяНовоеParams
    {
        
        #region Fields
        /// <summary>
        /// Тип "Нэйтан" в "textBoxNAME" надпись
        /// </summary>
        public string UITextBoxNAMEEditText = "Нэйтан";
        
        /// <summary>
        /// Тип "Джонс" в "textBoxLSTNAME" надпись
        /// </summary>
        public string UITextBoxLSTNAMEEditText = "Джонс";
        
        /// <summary>
        /// Тип "(439) 587-3458" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditText = "(439) 587-3458";
        
        /// <summary>
        /// Тип "459" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditSendKeys = "459";
        
        /// <summary>
        /// Тип "Master" в "textBoxEXP" надпись
        /// </summary>
        public string UITextBoxEXPEditText = "Master";
        
        /// <summary>
        /// Выберите "17-ИВТ-2" в "comboBoxGROUP" поле со списком
        /// </summary>
        public string UIComboBoxGROUPComboBoxSelectedItem = "17-ИВТ-2";
        
        /// <summary>
        /// Тип "Индиана" в "textBoxNAME" надпись
        /// </summary>
        public string UITextBoxNAMEEditText1 = "Индиана";
        
        /// <summary>
        /// Тип "Джонс" в "textBoxLSTNAME" надпись
        /// </summary>
        public string UITextBoxLSTNAMEEditText1 = "Джонс";
        
        /// <summary>
        /// Тип "(435) 943-8573" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditText1 = "(435) 943-8573";
        
        /// <summary>
        /// Тип "9" в "textBoxPHONE" надпись
        /// </summary>
        public string UITextBoxPHONEEditSendKeys1 = "9";
        
        /// <summary>
        /// Тип "Master" в "textBoxEXP" надпись
        /// </summary>
        public string UITextBoxEXPEditText1 = "Master";
        
        /// <summary>
        /// Выберите "18-ПРИ" в "comboBoxGROUP" поле со списком
        /// </summary>
        public string UIComboBoxGROUPComboBoxSelectedItem1 = "18-ПРИ";
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UITextBoxSearchTextWindow UITextBoxSearchTextWindow
        {
            get
            {
                if ((this.mUITextBoxSearchTextWindow == null))
                {
                    this.mUITextBoxSearchTextWindow = new UITextBoxSearchTextWindow(this);
                }
                return this.mUITextBoxSearchTextWindow;
            }
        }
        
        public UIНайтиПреподавателяGroup UIНайтиПреподавателяGroup
        {
            get
            {
                if ((this.mUIНайтиПреподавателяGroup == null))
                {
                    this.mUIНайтиПреподавателяGroup = new UIНайтиПреподавателяGroup(this);
                }
                return this.mUIНайтиПреподавателяGroup;
            }
        }
        
        public UIНайтиПреподавателяWindow UIНайтиПреподавателяWindow
        {
            get
            {
                if ((this.mUIНайтиПреподавателяWindow == null))
                {
                    this.mUIНайтиПреподавателяWindow = new UIНайтиПреподавателяWindow(this);
                }
                return this.mUIНайтиПреподавателяWindow;
            }
        }
        
        public UIНайтиWindow UIНайтиWindow
        {
            get
            {
                if ((this.mUIНайтиWindow == null))
                {
                    this.mUIНайтиWindow = new UIНайтиWindow(this);
                }
                return this.mUIНайтиWindow;
            }
        }
        
        public UITextBoxSPWindow UITextBoxSPWindow
        {
            get
            {
                if ((this.mUITextBoxSPWindow == null))
                {
                    this.mUITextBoxSPWindow = new UITextBoxSPWindow(this);
                }
                return this.mUITextBoxSPWindow;
            }
        }
        
        public UITextBoxDEPARTMENTWindow UITextBoxDEPARTMENTWindow
        {
            get
            {
                if ((this.mUITextBoxDEPARTMENTWindow == null))
                {
                    this.mUITextBoxDEPARTMENTWindow = new UITextBoxDEPARTMENTWindow(this);
                }
                return this.mUITextBoxDEPARTMENTWindow;
            }
        }
        
        public UITextBoxNMBWindow UITextBoxNMBWindow
        {
            get
            {
                if ((this.mUITextBoxNMBWindow == null))
                {
                    this.mUITextBoxNMBWindow = new UITextBoxNMBWindow(this);
                }
                return this.mUITextBoxNMBWindow;
            }
        }
        
        public UIДобавитьWindow UIДобавитьWindow
        {
            get
            {
                if ((this.mUIДобавитьWindow == null))
                {
                    this.mUIДобавитьWindow = new UIДобавитьWindow(this);
                }
                return this.mUIДобавитьWindow;
            }
        }
        
        public UITextBoxNAMEWindow UITextBoxNAMEWindow
        {
            get
            {
                if ((this.mUITextBoxNAMEWindow == null))
                {
                    this.mUITextBoxNAMEWindow = new UITextBoxNAMEWindow(this);
                }
                return this.mUITextBoxNAMEWindow;
            }
        }
        
        public UIДобавитьПреподавателWindow UIДобавитьПреподавателWindow
        {
            get
            {
                if ((this.mUIДобавитьПреподавателWindow == null))
                {
                    this.mUIДобавитьПреподавателWindow = new UIДобавитьПреподавателWindow(this);
                }
                return this.mUIДобавитьПреподавателWindow;
            }
        }
        
        public UITextBoxLSTNAMEWindow UITextBoxLSTNAMEWindow
        {
            get
            {
                if ((this.mUITextBoxLSTNAMEWindow == null))
                {
                    this.mUITextBoxLSTNAMEWindow = new UITextBoxLSTNAMEWindow(this);
                }
                return this.mUITextBoxLSTNAMEWindow;
            }
        }
        
        public UI__________Window UI__________Window
        {
            get
            {
                if ((this.mUI__________Window == null))
                {
                    this.mUI__________Window = new UI__________Window(this);
                }
                return this.mUI__________Window;
            }
        }
        
        public UITextBoxEXPWindow UITextBoxEXPWindow
        {
            get
            {
                if ((this.mUITextBoxEXPWindow == null))
                {
                    this.mUITextBoxEXPWindow = new UITextBoxEXPWindow(this);
                }
                return this.mUITextBoxEXPWindow;
            }
        }
        
        public UIComboBoxGROUPWindow UIComboBoxGROUPWindow
        {
            get
            {
                if ((this.mUIComboBoxGROUPWindow == null))
                {
                    this.mUIComboBoxGROUPWindow = new UIComboBoxGROUPWindow(this);
                }
                return this.mUIComboBoxGROUPWindow;
            }
        }
        
        public UIДобавитьWindow1 UIДобавитьWindow1
        {
            get
            {
                if ((this.mUIДобавитьWindow1 == null))
                {
                    this.mUIДобавитьWindow1 = new UIДобавитьWindow1(this);
                }
                return this.mUIДобавитьWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UITextBoxSearchTextWindow mUITextBoxSearchTextWindow;
        
        private UIНайтиПреподавателяGroup mUIНайтиПреподавателяGroup;
        
        private UIНайтиПреподавателяWindow mUIНайтиПреподавателяWindow;
        
        private UIНайтиWindow mUIНайтиWindow;
        
        private UITextBoxSPWindow mUITextBoxSPWindow;
        
        private UITextBoxDEPARTMENTWindow mUITextBoxDEPARTMENTWindow;
        
        private UITextBoxNMBWindow mUITextBoxNMBWindow;
        
        private UIДобавитьWindow mUIДобавитьWindow;
        
        private UITextBoxNAMEWindow mUITextBoxNAMEWindow;
        
        private UIДобавитьПреподавателWindow mUIДобавитьПреподавателWindow;
        
        private UITextBoxLSTNAMEWindow mUITextBoxLSTNAMEWindow;
        
        private UI__________Window mUI__________Window;
        
        private UITextBoxEXPWindow mUITextBoxEXPWindow;
        
        private UIComboBoxGROUPWindow mUIComboBoxGROUPWindow;
        
        private UIДобавитьWindow1 mUIДобавитьWindow1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITextBoxSearchTextWindow : WinWindow
    {
        
        public UITextBoxSearchTextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxSearchText";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxSearchTextEdit
        {
            get
            {
                if ((this.mUITextBoxSearchTextEdit == null))
                {
                    this.mUITextBoxSearchTextEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxSearchTextEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Имя преподавателя";
                    this.mUITextBoxSearchTextEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxSearchTextEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxSearchTextEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIНайтиПреподавателяGroup : WinGroup
    {
        
        public UIНайтиПреподавателяGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinControl.PropertyNames.Name] = "Найти Преподавателя";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinWindow UITextBoxSearchTextWindow
        {
            get
            {
                if ((this.mUITextBoxSearchTextWindow == null))
                {
                    this.mUITextBoxSearchTextWindow = new WinWindow(this);
                    #region Условия поиска
                    this.mUITextBoxSearchTextWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Имя преподавателя";
                    this.mUITextBoxSearchTextWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITextBoxSearchTextWindow.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxSearchTextWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITextBoxSearchTextWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIНайтиПреподавателяWindow : WinWindow
    {
        
        public UIНайтиПреподавателяWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "groupBox2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinGroup UIНайтиПреподавателяGroup
        {
            get
            {
                if ((this.mUIНайтиПреподавателяGroup == null))
                {
                    this.mUIНайтиПреподавателяGroup = new WinGroup(this);
                    #region Условия поиска
                    this.mUIНайтиПреподавателяGroup.SearchProperties[WinControl.PropertyNames.Name] = "Найти Преподавателя";
                    this.mUIНайтиПреподавателяGroup.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIНайтиПреподавателяGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIНайтиПреподавателяGroup;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIНайтиWindow : WinWindow
    {
        
        public UIНайтиWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "buttonSearch";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIНайтиButton
        {
            get
            {
                if ((this.mUIНайтиButton == null))
                {
                    this.mUIНайтиButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIНайтиButton.SearchProperties[WinButton.PropertyNames.Name] = "Найти";
                    this.mUIНайтиButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIНайтиButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIНайтиButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITextBoxSPWindow : WinWindow
    {
        
        public UITextBoxSPWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxSP";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxSPEdit
        {
            get
            {
                if ((this.mUITextBoxSPEdit == null))
                {
                    this.mUITextBoxSPEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxSPEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Кол - во студентов";
                    this.mUITextBoxSPEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxSPEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxSPEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITextBoxDEPARTMENTWindow : WinWindow
    {
        
        public UITextBoxDEPARTMENTWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxDEPARTMENT";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxDEPARTMENTEdit
        {
            get
            {
                if ((this.mUITextBoxDEPARTMENTEdit == null))
                {
                    this.mUITextBoxDEPARTMENTEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxDEPARTMENTEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxDEPARTMENTEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxDEPARTMENTEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITextBoxNMBWindow : WinWindow
    {
        
        public UITextBoxNMBWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxNMB";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxNMBEdit
        {
            get
            {
                if ((this.mUITextBoxNMBEdit == null))
                {
                    this.mUITextBoxNMBEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxNMBEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxNMBEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxNMBEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIДобавитьWindow : WinWindow
    {
        
        public UIДобавитьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "buttonGroup";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIДобавитьButton
        {
            get
            {
                if ((this.mUIДобавитьButton == null))
                {
                    this.mUIДобавитьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIДобавитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Добавить";
                    this.mUIДобавитьButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIДобавитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIДобавитьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITextBoxNAMEWindow : WinWindow
    {
        
        public UITextBoxNAMEWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxNAME";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxNAMEEdit
        {
            get
            {
                if ((this.mUITextBoxNAMEEdit == null))
                {
                    this.mUITextBoxNAMEEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxNAMEEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxNAMEEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxNAMEEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIДобавитьПреподавателWindow : WinWindow
    {
        
        public UIДобавитьПреподавателWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "groupBox1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinGroup UIДобавитьПреподавателGroup
        {
            get
            {
                if ((this.mUIДобавитьПреподавателGroup == null))
                {
                    this.mUIДобавитьПреподавателGroup = new WinGroup(this);
                    #region Условия поиска
                    this.mUIДобавитьПреподавателGroup.SearchProperties[WinControl.PropertyNames.Name] = "Добавить Преподавателя";
                    this.mUIДобавитьПреподавателGroup.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIДобавитьПреподавателGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIДобавитьПреподавателGroup;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITextBoxLSTNAMEWindow : WinWindow
    {
        
        public UITextBoxLSTNAMEWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxLSTNAME";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxLSTNAMEEdit
        {
            get
            {
                if ((this.mUITextBoxLSTNAMEEdit == null))
                {
                    this.mUITextBoxLSTNAMEEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxLSTNAMEEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxLSTNAMEEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxLSTNAMEEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UI__________Window : WinWindow
    {
        
        public UI__________Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxPHONE";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxPHONEEdit
        {
            get
            {
                if ((this.mUITextBoxPHONEEdit == null))
                {
                    this.mUITextBoxPHONEEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxPHONEEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxPHONEEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxPHONEEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITextBoxEXPWindow : WinWindow
    {
        
        public UITextBoxEXPWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBoxEXP";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBoxEXPEdit
        {
            get
            {
                if ((this.mUITextBoxEXPEdit == null))
                {
                    this.mUITextBoxEXPEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUITextBoxEXPEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBoxEXPEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBoxEXPEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIComboBoxGROUPWindow : WinWindow
    {
        
        public UIComboBoxGROUPWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "comboBoxGROUP";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIComboBoxGROUPComboBox
        {
            get
            {
                if ((this.mUIComboBoxGROUPComboBox == null))
                {
                    this.mUIComboBoxGROUPComboBox = new WinComboBox(this);
                    #region Условия поиска
                    this.mUIComboBoxGROUPComboBox.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIComboBoxGROUPComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIComboBoxGROUPComboBox;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIДобавитьWindow1 : WinWindow
    {
        
        public UIДобавитьWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "buttonTeacher";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIДобавитьButton
        {
            get
            {
                if ((this.mUIДобавитьButton == null))
                {
                    this.mUIДобавитьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIДобавитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Добавить";
                    this.mUIДобавитьButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIДобавитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIДобавитьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОшибкаWindow : WinWindow
    {
        
        public UIОшибкаWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Ошибка";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Ошибка");
            #endregion
        }
        
        #region Properties
        public UIОКWindow UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow(this);
                }
                return this.mUIОКWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIОКWindow mUIОКWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОКWindow : WinWindow
    {
        
        public UIОКWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Ошибка");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("Ошибка");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIПредупреждениеWindow : WinWindow
    {
        
        public UIПредупреждениеWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Предупреждение";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Предупреждение");
            #endregion
        }
        
        #region Properties
        public UIОКWindow1 UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow1(this);
                }
                return this.mUIОКWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIОКWindow1 mUIОКWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОКWindow1 : WinWindow
    {
        
        public UIОКWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Предупреждение");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("Предупреждение");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIБазаДанныхWindow : WinWindow
    {
        
        public UIБазаДанныхWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "База Данных";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("База Данных");
            #endregion
        }
        
        #region Properties
        public WinControl UIБазаДанныхDialog
        {
            get
            {
                if ((this.mUIБазаДанныхDialog == null))
                {
                    this.mUIБазаДанныхDialog = new WinControl(this);
                    #region Условия поиска
                    this.mUIБазаДанныхDialog.SearchProperties[UITestControl.PropertyNames.Name] = "База Данных";
                    this.mUIБазаДанныхDialog.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
                    this.mUIБазаДанныхDialog.WindowTitles.Add("База Данных");
                    #endregion
                }
                return this.mUIБазаДанныхDialog;
            }
        }
        
        public UIОКWindow2 UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow2(this);
                }
                return this.mUIОКWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIБазаДанныхDialog;
        
        private UIОКWindow2 mUIОКWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОКWindow2 : WinWindow
    {
        
        public UIОКWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("База Данных");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("База Данных");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
}
